### ISSUE TITLE
CSS Naming conventions

### ISSUE THREAD

**Issue by KennethAshley** [ValhallaVET/VeChain-New-Website#7]
To help keep clean CSS i think it might be a good idea to adopt naming conventions for our classes. In the past I have used the BEM naming convention and it worked well for small to large size sites. To get an understanding of BEM check it out [here](https://en.bem.info/methodology/key-concepts/). I propose we use a similar approach for this project.

I'm all ears if someone thinks of another approach.

**Comment by robinbastien** [comment]
👍👌 I too have been using BEM for years and support this. Another reason
I'm not a big fan of bootstrap is there's no clear separation of parent
components, modifiers, and children. Good way to go!
